### ISSUE TITLE
RuntimeError: Cuda error: 209[cudaLaunchKernel

### ISSUE THREAD

**Issue by jiaxiangshang** [NVlabs/nvdiffrast#75]
Hi, grouper,

My cuda is 10.1 or 11.0
The card is RTX 5000,
Pytorch version is 1.6.0

The error I get is 
`out, out_da = _get_plugin().interpolate_fwd(attr, rast, tri)
RuntimeError: Cuda error: 209[cudaLaunchKernel(func, gridSize, blockSize, args, 0, stream);]`

It seems the conflict of cuda, card, pyt versions, can you give some suggestions?

Best
Jiaxiang

**Comment by s-laine** [comment]
Quadro RTX 5000 is supported by Cuda 10.0 and later, but PyTorch 1.6.0 is too old to support Cuda 11.0 if that's what you have installed. Error 209 indicates that the Cuda compilation did not produce a kernel for the installed GPU architecture, and this compilation is handled by PyTorch, so that's where the problem probably is.

If upgrading PyTorch doesn't solve the problem, please try setting `verbose=True` in `nvdiffrast/torch/ops.py` line [84](https://github.com/NVlabs/nvdiffrast/blob/main/nvdiffrast/torch/ops.py#L84) and paste the output here. You may need to clear the PyTorch extension compilation directory to force a recompile.

**Comment by jiaxiangshang** [comment]
Hi s-laine,

It is solved by upgrading PyTorch, thank you very much.

Best
Jiaxiang
